#!/bin/bash
#
# ESP32 CSI Firmware Setup Script
# This script guides you through the configuration and flashing process
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WAVIRA_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  ESP32 CSI Firmware Setup Script${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Step 1: Check ESP-IDF
echo -e "${YELLOW}Step 1: Checking ESP-IDF environment...${NC}"
if [ -z "$IDF_PATH" ]; then
    echo -e "${RED}ESP-IDF is not sourced!${NC}"
    echo ""
    echo "Please run:"
    echo "  source \$HOME/esp/esp-idf/export.sh"
    echo ""
    echo "Then run this script again."
    exit 1
fi
echo -e "${GREEN}✓ ESP-IDF found: $IDF_PATH${NC}"
echo ""

# Step 2: Detect ESP32 port
echo -e "${YELLOW}Step 2: Detecting ESP32 serial port...${NC}"
PORTS=$(ls /dev/cu.usbserial* 2>/dev/null || true)
if [ -z "$PORTS" ]; then
    echo -e "${RED}No ESP32 device found!${NC}"
    echo "Please connect your ESP32 and try again."
    exit 1
fi

echo "Available ports:"
select PORT in $PORTS; do
    if [ -n "$PORT" ]; then
        echo -e "${GREEN}✓ Selected: $PORT${NC}"
        break
    fi
done
echo ""

# Step 3: Get configuration from user
echo -e "${YELLOW}Step 3: Configuration${NC}"
echo ""

# Wi-Fi SSID
read -p "Enter Wi-Fi SSID: " WIFI_SSID
if [ -z "$WIFI_SSID" ]; then
    echo -e "${RED}Wi-Fi SSID is required!${NC}"
    exit 1
fi

# Wi-Fi Password
read -sp "Enter Wi-Fi Password: " WIFI_PASSWORD
echo ""
if [ -z "$WIFI_PASSWORD" ]; then
    echo -e "${RED}Wi-Fi Password is required!${NC}"
    exit 1
fi

# Server IP
echo ""
echo "Your local IP addresses:"
ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print "  " $2}'
echo ""
read -p "Enter Server IP (e.g., 192.168.1.100): " SERVER_IP
if [ -z "$SERVER_IP" ]; then
    echo -e "${RED}Server IP is required!${NC}"
    exit 1
fi

# Server Port
read -p "Enter Server Port [8080]: " SERVER_PORT
SERVER_PORT=${SERVER_PORT:-8080}

# Device ID
read -p "Enter Device ID [esp32-001]: " DEVICE_ID
DEVICE_ID=${DEVICE_ID:-esp32-001}

# API Key
echo ""
echo -e "${YELLOW}API Key Setup:${NC}"
echo "  1. Start the server: python tools/csi_visualizer/api_server.py"
echo "  2. Register device to get API key, or use admin key"
echo ""
read -p "Enter API Key (or press Enter to skip for now): " API_KEY

echo ""
echo -e "${GREEN}Configuration Summary:${NC}"
echo "  Wi-Fi SSID:    $WIFI_SSID"
echo "  Server URL:    http://$SERVER_IP:$SERVER_PORT/api/v1/csi"
echo "  Device ID:     $DEVICE_ID"
echo "  Serial Port:   $PORT"
if [ -n "$API_KEY" ]; then
    echo "  API Key:       ${API_KEY:0:20}..."
else
    echo "  API Key:       (not set - configure in menuconfig)"
fi
echo ""

read -p "Proceed with this configuration? [Y/n]: " CONFIRM
CONFIRM=${CONFIRM:-Y}
if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
fi

# Step 4: Create sdkconfig with user settings
echo ""
echo -e "${YELLOW}Step 4: Applying configuration...${NC}"

cd "$SCRIPT_DIR"

# Create a temporary sdkconfig.local file
cat > sdkconfig.local << EOF
# User Configuration (generated by setup.sh)
CONFIG_WAVIRA_WIFI_SSID="$WIFI_SSID"
CONFIG_WAVIRA_WIFI_PASSWORD="$WIFI_PASSWORD"
CONFIG_WAVIRA_SERVER_URL="http://$SERVER_IP:$SERVER_PORT/api/v1/csi"
CONFIG_WAVIRA_BATCH_ENDPOINT="http://$SERVER_IP:$SERVER_PORT/api/v1/csi/batch"
CONFIG_WAVIRA_DEVICE_ID="$DEVICE_ID"
EOF

if [ -n "$API_KEY" ]; then
    echo "CONFIG_WAVIRA_API_KEY=\"$API_KEY\"" >> sdkconfig.local
fi

# Append local config to sdkconfig.defaults if needed
if [ -f sdkconfig ]; then
    # Backup existing sdkconfig
    cp sdkconfig sdkconfig.backup
fi

# Apply defaults and local config
cat sdkconfig.defaults sdkconfig.local > sdkconfig.combined
mv sdkconfig.combined sdkconfig

echo -e "${GREEN}✓ Configuration applied${NC}"
echo ""

# Step 5: Build
echo -e "${YELLOW}Step 5: Building firmware...${NC}"
idf.py build

if [ $? -ne 0 ]; then
    echo -e "${RED}Build failed!${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Build successful${NC}"
echo ""

# Step 6: Flash
echo -e "${YELLOW}Step 6: Flashing to ESP32...${NC}"
read -p "Ready to flash. Press Enter to continue (or Ctrl+C to cancel)..."

idf.py -p "$PORT" flash

if [ $? -ne 0 ]; then
    echo -e "${RED}Flash failed!${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Flash successful${NC}"
echo ""

# Step 7: Done
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}  Setup Complete!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "Next steps:"
echo "  1. Start the server (if not running):"
echo "     cd $WAVIRA_ROOT/tools/csi_visualizer"
echo "     python api_server.py --port $SERVER_PORT"
echo ""
echo "  2. Monitor ESP32 output:"
echo "     idf.py -p $PORT monitor"
echo ""
echo "  3. Check server health:"
echo "     curl http://$SERVER_IP:$SERVER_PORT/api/v1/health"
echo ""

# Cleanup
rm -f sdkconfig.local

# Ask if user wants to start monitor
read -p "Start serial monitor now? [Y/n]: " START_MONITOR
START_MONITOR=${START_MONITOR:-Y}
if [[ "$START_MONITOR" =~ ^[Yy]$ ]]; then
    echo ""
    echo -e "${YELLOW}Starting monitor (Ctrl+] to exit)...${NC}"
    idf.py -p "$PORT" monitor
fi
